name: PHP Linter

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  PHP:
    runs-on: ubuntu-latest
    container:
      image: php:8.1-cli-alpine
    steps:
      - uses: actions/checkout@v3
      - run: find . -name '*.php' | xargs -trn 1 php -l
